apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-inference
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: 'https://github.com/sergyinfo/MLOps.git'
    targetRevision: final-project
    path: helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true